process.env.DATABASE_URL = 'postgres://postgres@127.0.0.1:5547/template1?sslmode=disable';
delete process.env.FURIA_DATA;
const { startServer } = await import('./src/web/server.ts');
const { requestClaim } = await import('./src/db/claim_repo.ts');
const { signup, owns } = await import('./src/db/auth_repo.ts');
const { createClubWithTeam } = await import('./src/db/repo.ts');
const { setBranding } = await import('./src/db/entity_repo.ts');
const app = await startServer(0);
let pass=0,fail=0; const ok=(n,c)=>{console.log(`  ${c?'PASS':'FAIL'} ${n}`);c?pass++:fail++;};
const t = await app.db.query(`SELECT to_regclass('public.claim_request')::text r`);
ok('claim_request table exists on real Postgres', t.rows[0].r === 'public.claim_request');
const { clubId } = await createClubWithTeam(app.db, 'FC Wire', app.ids.football);
await setBranding(app.db, 'club', clubId, { links:{ website:'https://fcwire.de' }});
const acc = (await signup(app.db, 'boss@fcwire.de','Boss','pw123456')).accountId;
const r = await requestClaim(app.db, { id: acc, email:'boss@fcwire.de' }, 'club', clubId);
ok('email-domain claim verified over real PG', r.status==='verified' && await owns(app.db, acc, 'club', clubId));
console.log(`  APP RSS=${(process.memoryUsage().rss/1048576).toFixed(0)}MB`);
await app.close();
console.log(`──── ${pass} passed, ${fail} failed ────`);
process.exit(fail>0?1:0);
