import { startServer } from './src/web/server.ts';
import { createClaim, formatSpots } from './src/db/claim_rail_repo.ts';
import { addFormat, formatCounts } from './src/db/event_format_repo.ts';
import { createScheduledEvent } from './src/db/events_repo.ts';
const app = await startServer(0); const db = app.db;
const h = app.ids.athletes[0].id;
const eid = await createScheduledEvent(db, { hostKind:'athlete', hostId:h, title:'CAP', startsAt:new Date(Date.now()+864e5).toISOString(), locationKind:'hybrid' });
const ip = await addFormat(db, { eventId:eid, kind:'in_person', label:'In person', capacity:2, maxPerPerson:4, sort:0 });
const st = await addFormat(db, { eventId:eid, kind:'stream', label:'YouTube', capacity:null, maxPerPerson:1, sort:1 });
const fan = async (n:string) => (await db.query<any>(`INSERT INTO fan (display_name) VALUES ($1) RETURNING id`,[n])).rows[0].id;
const f1=await fan('F1'), f2=await fan('F2'), f3=await fan('F3'), f4=await fan('F4');
const c1 = await createClaim(db,{eventId:eid,fanId:f1,capacity:2,mode:'open',formatId:ip,partySize:2,maxPerPerson:4});
console.log('F1 takes 2 of 2 hall spots     →', c1.status, 'party='+c1.partySize);
const c2 = await createClaim(db,{eventId:eid,fanId:f2,capacity:2,mode:'open',formatId:ip,partySize:1,maxPerPerson:4});
console.log('F2 wants the hall, it is full  →', c2.status, '(expect waitlisted)');
const c3 = await createClaim(db,{eventId:eid,fanId:f3,capacity:null,mode:'open',formatId:st,partySize:1,maxPerPerson:1});
console.log('F3 takes the stream            →', c3.status, '(expect claimed — hall full must NOT close the stream)');
const c4 = await createClaim(db,{eventId:eid,fanId:f4,capacity:null,mode:'open',formatId:st,partySize:99,maxPerPerson:1});
console.log('F4 posts party_size=99 on max-1→ stored party=' + c4.partySize, '(expect 1)');
console.log('hall spots:', JSON.stringify(await formatSpots(db, ip, 2)));
const fc = await formatCounts(db, eid);
console.log('organiser sees:', fc.map(x=>`${x.label}=${x.going} going`).join(', '), '(hall must be 2 people, not 1 claim)');
process.exit(0);
