import { writeFileSync } from 'node:fs';
import { startServer } from './src/web/server.ts';
import { createScheduledEvent } from './src/db/events_repo.ts';
import { addFormat } from './src/db/event_format_repo.ts';
import { notify } from './src/db/notif_repo.ts';
const app:any = await startServer(0);
const base=`http://localhost:${app.port}`, rico=app.ids.athletes[0].id, club=app.ids.clubs[0].id, db=app.db, fan=app.ids.fanId;
await createScheduledEvent(db,{hostKind:'athlete',hostId:rico,title:'Fight Night — LIVE',startsAt:new Date(Date.now()-20*60000).toISOString(),location:'Berlin',admission:'open',locationKind:'hybrid'});
const champ = await createScheduledEvent(db,{hostKind:'club',hostId:club,title:'German Championship Final',startsAt:new Date(Date.now()+7*864e5).toISOString(),location:'Olympiastadion, Berlin',admission:'open',locationKind:'hybrid'});
await addFormat(db,{eventId:champ,kind:'in_person',label:'In person',requiresTicket:true,priceCents:2500,capacity:200,sort:0});
await addFormat(db,{eventId:champ,kind:'stream',label:'TikTok Live',channelUrl:'https://tiktok.com/@x/live',requiresTicket:false,sort:1});
await addFormat(db,{eventId:champ,kind:'stream',label:'Sportdeutschland.TV',channelUrl:'https://sportdeutschland.tv/x',requiresTicket:false,sort:2});
await notify(db,{fanId:fan,kind:'claim_new',headline:'Alex confirmed — In person.',href:'/'});
const w=async(n:string,p:string,o?:any)=>{const t=await(await fetch(base+p,o)).text();writeFileSync('../'+n,t);console.log(n,t.length);};
await w('horda-DESIGN-athlete.html',`/athlete/${rico}`);
await w('horda-DESIGN-club.html',`/club/${club}`);
await w('horda-DESIGN-connections.html',`/athlete/${rico}/connections`);
await w('horda-DESIGN-event-multiformat.html',`/e/${champ}?guest=1`);
await w('horda-DESIGN-erkunden-loggedin.html','/');
process.exit(0);
