import { startServer } from './src/web/server.ts';
import * as fs from 'node:fs';
const app = await startServer(0); const base='http://127.0.0.1:'+app.port;
const club = app.ids.clubs[0].id;
const ev = (await app.db.query<{id:string}>(`SELECT id FROM event WHERE starts_at > now() ORDER BY starts_at LIMIT 1`)).rows[0].id;
fs.writeFileSync('/tmp/c_landing.html', await (await fetch(base+'/?guest=1')).text());
fs.writeFileSync('/tmp/c_about.html', await (await fetch(base+'/about?guest=1')).text());
fs.writeFileSync('/tmp/c_event.html', await (await fetch(base+`/e/${ev}?guest=1`)).text());
fs.writeFileSync('/tmp/c_club.html', await (await fetch(base+`/club/${club}?guest=1`)).text());
console.log('ok');
process.exit(0);
